import {Barlow, Inter} from 'next/font/google';

import './globals.css';
import Header from './src/components/common/Header';

const inter = Inter({subsets: ['latin']});

const barlow = Barlow({
  display: 'swap',
  variable: '--font-barlow',
  subsets: ['latin'],
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="ko">
      <body className={`${inter.className}, ${barlow.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
