import {Barlow} from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';
import Header from './src/components/common/Header';

// const inter = Inter({subsets: ['latin']});

const myFont = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
});

const barlow = Barlow({
  display: 'swap',
  variable: '--font-barlow',
  subsets: ['latin'],
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="ko">
      <body className={`${myFont.className} ${barlow.variable}`}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
